version: "2"

exclude_patterns:
- "src/test/"
- "src/main/java/db/migration/"
- "**/*.js"
- "**/*.css"


checks:
    similar-code:
        enabled: false
    identical-code:
        enabled: false

plugins:
  checkstyle:
      enabled: true
      config:
          file: ".codeclimate/checkstyle.xml"
      checks:
          com.puppycrawl.tools.checkstyle.checks.coding.MagicNumberCheck:
              enabled: false
  sonar-java:
      enabled: true
      config:
          minimum_severity: critical