spring:
  datasource:
    url: jdbc:postgresql://db:5432/events

  mail:
    host: mailcatcher
    port: 1025

  security:
    oauth2:
      client:
        provider:
          wisvchconnect:
            issuer-uri: http://oidc:8080
            authorization-uri: http://localhost:3093/connect/authorize
